Step graph from file
allenai/tango pull request #193
Opened 2022-02-12 02:10 UTC by dirkgr

In the https://github.com/allenai/lm-robustness project, I want to parse a Jsonnet file and then interact with the step graph programmatically. This makes it easy.

2022-02-14 21:57 UTC, AkshitaB requested changes
Looks good. Will be helpful to have a test case.

2022-02-15 01:33 UTC, dirkgr commented
Right you are. [c5c2490](https://github.com/allenai/tango/pull/193/commits/c5c2490d73bd8df651ba36433dd25476ce7608d2)

2022-02-15 02:37 UTC, dirkgr commented
I found two different problems while writing that test. We are very dependent on the order the tests run in. This is not ideal.

2022-02-15 23:14 UTC, AkshitaB approved these changes

2022-02-15 23:16 UTC, merged