Finetuning
allenai/tango pull request #255
Opened 2022-04-04 06:14 UTC by AkshitaB

Fixes #

Changes proposed in this pull request:

-

## Before submitting

- [ ] I've read and followed all steps in the [Making a pull request](https://github.com/allenai/tango/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/allenai/tango/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

2022-04-12 20:58 UTC, dirkgr requested changes

2022-04-15 06:36 UTC, AkshitaB commented on examples/finetune/snli_steps.py
> +class SubsetData(Step):
Will work on it separately: https://github.com/allenai/tango/issues/268 This is technically unrelated to finetuning.

2022-04-15 07:12 UTC, AkshitaB commented on tango/integrations/transformers/finetune.py
> +        model: Lazy[Model],
This can be done once we fix this: https://github.com/allenai/tango/pull/269

2022-04-15 07:22 UTC, AkshitaB commented on tango/integrations/transformers/finetune.py
> +        model: Lazy[Model],
And this: https://github.com/allenai/tango/issues/270

2022-04-19 22:16 UTC, dirkgr approved these changes

2022-04-19 22:23 UTC, merged