Fix bug with Beaker executor
allenai/tango pull request #430
Opened 2022-09-29 21:46 UTC by epwalsh

The Beaker executor would hang at the end of a run if a step failed that was a dependency of another step.

This also makes the Beaker executor periodically print out updates so you know how many and which steps it's still waiting on.

2022-09-29 21:46 UTC, epwalsh commented on tango/integrations/beaker/executor.py
> +                                steps_left_to_run.discard(step)
This line fixes the bug. The other additions below are just for the progress updates.

2022-10-03 19:59 UTC, dirkgr requested changes
I like everything except the variable name 😅.

2022-10-03 19:59 UTC, dirkgr commented on tango/integrations/beaker/executor.py
> +                        "Waiting on %d running steps...",
"Waiting for". If you're waiting on someone, you're bringing them water.

2022-10-03 20:15 UTC, dirkgr approved these changes

2022-10-03 20:21 UTC, merged