Use commit at time executor is instantiated
allenai/tango pull request #605
Opened 2023-10-04 20:29 UTC by epwalsh

For the `BeakerExecutor`, instead of using the HEAD commit at the time each step is submitted.

2023-10-04 21:44 UTC, AkshitaB approved these changes
LGTM

2023-10-04 21:46 UTC, AkshitaB commented on tango/integrations/beaker/executor.py
> +        self._github_account, self._github_repo = self._parse_git_remote(git)
```suggestion
        self._github_account, self._github_repo = self._parse_git_remote(git.remote)
```

2023-10-04 21:47 UTC, AkshitaB requested changes
Ah, missed `git.remote` error

2023-10-04 23:50 UTC, AkshitaB approved these changes

2023-10-10 00:34 UTC, dirkgr approved these changes

2023-10-10 02:45 UTC, merged